/*

 LEVELMAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\kristoffer\Downloads\gbtd22\LevelTileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define LevelMapWidth 20
#define LevelMapHeight 18
#define LevelMapBank 0

extern unsigned char LevelMap[];

/* End of LEVELMAP.H */
